/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingImport } from './routes/setting'
import { Route as SectionImport } from './routes/section'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SettingRoute = SettingImport.update({
  path: '/setting',
  getParentRoute: () => rootRoute,
} as any)

const SectionRoute = SectionImport.update({
  path: '/section',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/section': {
      id: '/section'
      path: '/section'
      fullPath: '/section'
      preLoaderRoute: typeof SectionImport
      parentRoute: typeof rootRoute
    }
    '/setting': {
      id: '/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof SettingImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/section': typeof SectionRoute
  '/setting': typeof SettingRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/section': typeof SectionRoute
  '/setting': typeof SettingRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/section': typeof SectionRoute
  '/setting': typeof SettingRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/section' | '/setting'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/section' | '/setting'
  id: '__root__' | '/' | '/section' | '/setting'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SectionRoute: typeof SectionRoute
  SettingRoute: typeof SettingRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SectionRoute: SectionRoute,
  SettingRoute: SettingRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/section",
        "/setting"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/section": {
      "filePath": "section.tsx"
    },
    "/setting": {
      "filePath": "setting.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
